sudo: false
language: php
php:
  - 5.3
  - 5.6
  - 7
env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
matrix:
  exclude:
    - php: 5.3
      env: SYMFONY_VERSION="3.0.*"

before_script:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer require --dev --no-interaction symfony/symfony:${SYMFONY_VERSION}
